{% set name = "skl2onnx" %}
{% set version = "1.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onnx/sklearn-onnx/archive/{{ version }}.tar.gz
  sha256: 724fcfb5d5bab68833ce4164d62aaaf84d91c39161544b597f52077faa7217af

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  string: py_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six {{ six }}
    - numpy {{ numpy }}
    - scipy {{ scipy }}
    - protobuf {{ protobuf }}
    - onnx {{ onnx }}
    - scikit-learn >=0.19
    - onnxconverter-common {{ onnxconverter_common }}

test:
  imports:
    - skl2onnx

about:
  home: https://github.com/onnx/sklearn-onnx
  summary: Convert scikit-learn models and pipelines to ONNX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
