{% set name = "skl2onnx" %}
{% set version = "1.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onnx/sklearn-onnx/archive/v{{ version }}.tar.gz
  sha256: 782216a8cab111e8db7b0bb63cc8b4077b4ae29e3df770cfd7a47b7a5c3d8bd5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  string: pyh{{ PKG_HASH }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six {{ six }}
    - numpy {{ numpy }}
    - scipy {{ scipy }}
    - protobuf {{ protobuf }}
    - onnx {{ onnx }}
    - scikit-learn >=0.19
    - onnxconverter-common {{ onnxconverter_common }}
    - packaging

test:
  imports:
    - skl2onnx

about:
  home: https://github.com/onnx/sklearn-onnx
  summary: Convert scikit-learn models and pipelines to ONNX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
